<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationIcon>..\mic_on.ico</ApplicationIcon>
    <Version>2.0.0</Version>
    <AssemblyName>MicMute</AssemblyName>
    <RootNamespace>MicMute</RootNamespace>
    <Nullable>disable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <NoWarn>CA1416</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="..\mic_on.ico" LogicalName="mic_on.ico" />
    <EmbeddedResource Include="..\mic_off.ico" LogicalName="mic_off.ico" />
  </ItemGroup>

</Project>
